### ISSUE TITLE
Folders vagrant-apim/vagrant-apim-vagrant-box-automation seems to be redundant

### ISSUE THREAD

**Issue by imesh** [wso2/vagrant-apim#4]
**Description:**
I think the folders ```vagrant-apim/vagrant-apim-vagrant-box-automation``` added in #2 are redundant since the repository already mentions its dedicated for Vagrant files of API Manager.

I would like to propose to rename above folders as follows:
vagrant-boxes/

**Comment by imesh** [comment]
@ctienshi As I see the new folder structure as follows:

/vagrantboxes/
/vagrantfiles/

Here vagrantfiles folder only contains one Vagrantfile. If so shall we move it to the root folder rather than creating a separate folder called vagrantfiles. This will allow users to directly execute vagrant commands on the root folder. Most importantly, this is the convention followed in most vagrant repositories:

https://github.com/dcos/dcos-vagrant
https://github.com/pires/kubernetes-vagrant-coreos-cluster

**Comment by imesh** [comment]
@ctienshi @VimukthiPerera @DilanUA @msmshariq @chamithkumarage 
Would you mind sharing your thoughts on the design of the folder structure for vagrant-apim? I think it would be better if we can discuss it here and then apply it to all WSO2 vagrant repositories. WDYT?

Please find my proposal below:

````bash
/boxes/  # include scripts required for building Vagrant boxes
/boxes/dist/  # copy WSO2 and dependent distributions required
/mysql/scripts/  # include SQL scripts required for creating databases
/<wso2-product-component>/  # will correspond to wso2 component's product home directory
/<wso2-product-component>/repository/components/lib/
/<wso2-product-component>/repository/conf/
/<wso2-product-component>/repository/deployment/server/
/Vagrantfile # Vagrantfile for automating the deployment on VirtualBox
````bash

For products like EI if we think we need multiple Vagrantfiles may be we can introduce a solution folder:
````bash
/boxes/  # include scripts required for building Vagrant boxes
/boxes/dist/  # copy WSO2 and dependent distributions required
/<solution>/mysql/scripts/  # include SQL scripts required for creating databases
/<solution>/<wso2-product-component>/  # will correspond to wso2 component's product home directory
/<solution>/<wso2-product-component>/repository/components/lib/
/<solution>/<wso2-product-component>/repository/conf/
/<solution>/<wso2-product-component>/repository/deployment/server/
/<solution>/Vagrantfile # Vagrantfile for automating the deployment on VirtualBox
````bash

Appreciate your thoughts on this!

**Comment by ctienshi** [comment]
@imesh +1 to idea of the folder structure. For a product like EI would the solution folder be renamed according to the combination of profiles?

**Comment by VimukthiPerera** [comment]
@imesh @ctienshi I think this folder structure is a little bit confusing because of the Vagrantfile in the root.
IMO, the root should have two folders. 
1. boxes (This should contain the Vagrantfile and the other resources which are used to build the boxes)
2. <appropriate name> (This should contain the Vagrantfile and the resources which are used to run the boxes)
3. README.md
Inside these folders we can have a structure like @imesh have proposed. WDYT?

**Comment by chirangaalwis** [comment]
@imesh why don't we move out the `boxes` section out of each product Vagrant resource repository and have one common repository which holds Vagrant box creation resources?

Box creation implementation was constructed with a generic design which allows users to simply provide the product profile name and version. As you pointed out in one of the offline discussions I agree with the fact that usability aspect has to be considered (if we maintain two separate repositories). But in the long term, I feel that this approach would greatly facilitate code maintenance. Plus, I don't think that maintaining two repositories would greatly tarnish the user experience, if we provide proper guidelines.

**Comment by chirangaalwis** [comment]
@imesh IMO the existing folder structure is clearer than the suggested one. True that existing, popular Vagrant resource repositories follow a structure where the Vagrantfile is maintained in the project root. But in this case, since we are maintaining the Vagrant box creation logic also, in the same repository, I feel the existing structure is a better solution.

**Comment by ctienshi** [comment]
We could move the vagrantfile to the root folder in a scenario where the box creation is absent. I think Chiranga and Vimukthi have a valid point here. Adding the vagrantfile to the root folder along with the boxes folder might confuse the users. Some might think it is a part of the vagrantfile, which is required to deploy the server. Boxes folder contains the resources to create the boxes and the vagranfile folder contains the resources to deploy the servers. Since these are two separate things it would be better to keep them separately. Plus customers with a valid subscription won't be needing to create boxes by themselves, since they will be downloading the corresponding boxes from the server. Therefore the "boxes" folder would be redundant for those users in those scenarios and it would be better to keep the "boxes" and "vagrantfile" folders separately to minimize the confusion. @imesh WDYT?

**Comment by imesh** [comment]
@VimukthiPerera @chirangaalwis @ctienshi +1 Agree with the points that you have mentioned. Let's move the Vagrantfile to a subfolder. Thanks!

**Comment by DilanUA** [comment]
Closing based on above comment.
